Add support for 13.6.4
beeper/mac-registration-provider pull request #32
Opened 2024-02-14 22:14 UTC by r3dlobst3r

This PR will add support for users on Ventura 13.6.4.

2024-02-16 16:47 UTC, jetfir3 commented
The 13.6.4 offsets seem to match all of the previous 13.6.x releases, only the binary hash changes.

PR should only need the following:
```
	// macOS 13.6.4
        hexToByte32("8f22dcfda56a4d3c38931f20fe33db1a6720e4d8571e452aa5a8b56b4c69842a"): offsets_13_6,
```

2024-02-20 15:51 UTC, bderagon commented
looks right to me, can we get this merged?

2024-02-21 16:20 UTC, jetfir3 commented on nac/offsets.go
> +        hexToByte32("8f22dcfda56a4d3c38931f20fe33db1a6720e4d8571e452aa5a8b56b4c69842a"): offsets_13_6_4,
This should be `offsets_13_6,` and not `offsets_13_6_4,` (due to the recent removal of superfluous offsets)

2024-02-29 23:56 UTC, xChickens approved these changes

2024-02-29 23:58 UTC, xChickens commented
Your commit has spaces and not tabs so the lint is failing

2024-03-01 00:34 UTC, xChickens requested changes

2024-03-01 00:34 UTC, xChickens commented on nac/offsets.go
> +        hexToByte32("8f22dcfda56a4d3c38931f20fe33db1a6720e4d8571e452aa5a8b56b4c69842a"): offsets_13_6,
Spaced using spaces instead of tabs

2024-03-01 01:55 UTC, 0xdevalias commented
Duplicate PR?

- https://github.com/beeper/mac-registration-provider/pull/35

2024-03-01 10:08 UTC, closed without merging